name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**
      - "**/README.md"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new_version }}
    steps:
      - name: Check if push is from GitHub Actions
        run: |
          if [ "${{ github.actor }}" == "github-actions[bot]" ]; then
            echo "Push triggered by GitHub Actions bot. Skipping workflow."
            exit 78
          fi
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Bump version
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . ./.github/scripts/bump_version.sh
          npm version $new_version --no-git-tag-version
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .github/
            .git/
            dist/
            public/
            src/
            types/
            package.json
            package-lock.json
            tsconfig.json
            vite.config.ts
            vite.config.page.ts

  publish-github-release:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEW_VERSION: ${{ needs.build.outputs.new-version }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com/KingMaj0r/harmony-core.git
          git checkout -b "V${{ env.NEW_VERSION }}"
      - name: Add Files
        run: |
          git add dist/
          git add package.json/
          git add public/
          git add types/
          git commit -m "${{ env.NEW_VERSION }}"
      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "V${{ needs.build.outputs.new-version }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: V${{ env.NEW_VERSION }}
          target_commitish: "V${{ needs.build.outputs.new-version }}"
          generate_release_notes: true
          make_latest: true

  publish-npm:
    needs: [build, publish-github-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: [build, publish-github-release]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-github:
    needs: [build, publish-github-release, publish-npm, publish-gpr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - name: Release all the changes to GitHub repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ needs.build.outputs.new-version }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to $NEW_VERSION"
          git remote set-url origin git@github.com:KingMaj0r/harmony-core.git
          git push --set-upstream origin main
