name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new_version }}
    steps:
      - name: Check if push is from GitHub Actions
        run: |
          if [ "${{ github.actor }}" == "github-actions[bot]" ]; then
            echo "Push triggered by GitHub Actions bot. Skipping workflow."
            exit 78
          fi
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Bump version
        id: bump-version
        run: |
          . ./.github/scripts/bump_version.sh
          npm version $new_version --no-git-tag-version
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
      - name: publish changes to github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ steps.bump-version.outputs.new-version }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add package.json
          git commit -m "Bump version to $NEW_VERSION"
          git push -u origin main
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .github/
            .git/
            dist/
            public/
            src/
            types/
            package.json
            package-lock.json
            tsconfig.json
            vite.config.ts
            vite.config.page.ts

  publish-npm:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
